// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/biodata/biodata.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Biodata struct {
	Nik                  int32    `protobuf:"varint,1,opt,name=nik,proto3" json:"nik,omitempty"`
	Nama                 string   `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	Jk                   string   `protobuf:"bytes,3,opt,name=jk,proto3" json:"jk,omitempty"`
	Alamat               string   `protobuf:"bytes,4,opt,name=alamat,proto3" json:"alamat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Biodata) Reset()         { *m = Biodata{} }
func (m *Biodata) String() string { return proto.CompactTextString(m) }
func (*Biodata) ProtoMessage()    {}
func (*Biodata) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{0}
}

func (m *Biodata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Biodata.Unmarshal(m, b)
}
func (m *Biodata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Biodata.Marshal(b, m, deterministic)
}
func (m *Biodata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Biodata.Merge(m, src)
}
func (m *Biodata) XXX_Size() int {
	return xxx_messageInfo_Biodata.Size(m)
}
func (m *Biodata) XXX_DiscardUnknown() {
	xxx_messageInfo_Biodata.DiscardUnknown(m)
}

var xxx_messageInfo_Biodata proto.InternalMessageInfo

func (m *Biodata) GetNik() int32 {
	if m != nil {
		return m.Nik
	}
	return 0
}

func (m *Biodata) GetNama() string {
	if m != nil {
		return m.Nama
	}
	return ""
}

func (m *Biodata) GetJk() string {
	if m != nil {
		return m.Jk
	}
	return ""
}

func (m *Biodata) GetAlamat() string {
	if m != nil {
		return m.Alamat
	}
	return ""
}

type CreateBiodataRequest struct {
	Biodata              *Biodata `protobuf:"bytes,1,opt,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBiodataRequest) Reset()         { *m = CreateBiodataRequest{} }
func (m *CreateBiodataRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBiodataRequest) ProtoMessage()    {}
func (*CreateBiodataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{1}
}

func (m *CreateBiodataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBiodataRequest.Unmarshal(m, b)
}
func (m *CreateBiodataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBiodataRequest.Marshal(b, m, deterministic)
}
func (m *CreateBiodataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBiodataRequest.Merge(m, src)
}
func (m *CreateBiodataRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBiodataRequest.Size(m)
}
func (m *CreateBiodataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBiodataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBiodataRequest proto.InternalMessageInfo

func (m *CreateBiodataRequest) GetBiodata() *Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

type CreateBiodataResponse struct {
	Biodata              *Biodata `protobuf:"bytes,1,opt,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBiodataResponse) Reset()         { *m = CreateBiodataResponse{} }
func (m *CreateBiodataResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBiodataResponse) ProtoMessage()    {}
func (*CreateBiodataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{2}
}

func (m *CreateBiodataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBiodataResponse.Unmarshal(m, b)
}
func (m *CreateBiodataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBiodataResponse.Marshal(b, m, deterministic)
}
func (m *CreateBiodataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBiodataResponse.Merge(m, src)
}
func (m *CreateBiodataResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBiodataResponse.Size(m)
}
func (m *CreateBiodataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBiodataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBiodataResponse proto.InternalMessageInfo

func (m *CreateBiodataResponse) GetBiodata() *Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

type ReadBiodataRequest struct {
	Nik                  int32    `protobuf:"varint,1,opt,name=nik,proto3" json:"nik,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBiodataRequest) Reset()         { *m = ReadBiodataRequest{} }
func (m *ReadBiodataRequest) String() string { return proto.CompactTextString(m) }
func (*ReadBiodataRequest) ProtoMessage()    {}
func (*ReadBiodataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{3}
}

func (m *ReadBiodataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBiodataRequest.Unmarshal(m, b)
}
func (m *ReadBiodataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBiodataRequest.Marshal(b, m, deterministic)
}
func (m *ReadBiodataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBiodataRequest.Merge(m, src)
}
func (m *ReadBiodataRequest) XXX_Size() int {
	return xxx_messageInfo_ReadBiodataRequest.Size(m)
}
func (m *ReadBiodataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBiodataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBiodataRequest proto.InternalMessageInfo

func (m *ReadBiodataRequest) GetNik() int32 {
	if m != nil {
		return m.Nik
	}
	return 0
}

type ReadBiodataResponse struct {
	Biodata              *Biodata `protobuf:"bytes,1,opt,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadBiodataResponse) Reset()         { *m = ReadBiodataResponse{} }
func (m *ReadBiodataResponse) String() string { return proto.CompactTextString(m) }
func (*ReadBiodataResponse) ProtoMessage()    {}
func (*ReadBiodataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{4}
}

func (m *ReadBiodataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadBiodataResponse.Unmarshal(m, b)
}
func (m *ReadBiodataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadBiodataResponse.Marshal(b, m, deterministic)
}
func (m *ReadBiodataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadBiodataResponse.Merge(m, src)
}
func (m *ReadBiodataResponse) XXX_Size() int {
	return xxx_messageInfo_ReadBiodataResponse.Size(m)
}
func (m *ReadBiodataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadBiodataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadBiodataResponse proto.InternalMessageInfo

func (m *ReadBiodataResponse) GetBiodata() *Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

type UpdateBiodataRequest struct {
	Biodata              *Biodata `protobuf:"bytes,1,opt,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBiodataRequest) Reset()         { *m = UpdateBiodataRequest{} }
func (m *UpdateBiodataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBiodataRequest) ProtoMessage()    {}
func (*UpdateBiodataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{5}
}

func (m *UpdateBiodataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBiodataRequest.Unmarshal(m, b)
}
func (m *UpdateBiodataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBiodataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBiodataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBiodataRequest.Merge(m, src)
}
func (m *UpdateBiodataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBiodataRequest.Size(m)
}
func (m *UpdateBiodataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBiodataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBiodataRequest proto.InternalMessageInfo

func (m *UpdateBiodataRequest) GetBiodata() *Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

type UpdateBiodataResponse struct {
	Biodata              *Biodata `protobuf:"bytes,1,opt,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBiodataResponse) Reset()         { *m = UpdateBiodataResponse{} }
func (m *UpdateBiodataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBiodataResponse) ProtoMessage()    {}
func (*UpdateBiodataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{6}
}

func (m *UpdateBiodataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBiodataResponse.Unmarshal(m, b)
}
func (m *UpdateBiodataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBiodataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBiodataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBiodataResponse.Merge(m, src)
}
func (m *UpdateBiodataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBiodataResponse.Size(m)
}
func (m *UpdateBiodataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBiodataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBiodataResponse proto.InternalMessageInfo

func (m *UpdateBiodataResponse) GetBiodata() *Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

type DeleteBiodataRequest struct {
	Nik                  int32    `protobuf:"varint,1,opt,name=nik,proto3" json:"nik,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBiodataRequest) Reset()         { *m = DeleteBiodataRequest{} }
func (m *DeleteBiodataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBiodataRequest) ProtoMessage()    {}
func (*DeleteBiodataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{7}
}

func (m *DeleteBiodataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBiodataRequest.Unmarshal(m, b)
}
func (m *DeleteBiodataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBiodataRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBiodataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBiodataRequest.Merge(m, src)
}
func (m *DeleteBiodataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBiodataRequest.Size(m)
}
func (m *DeleteBiodataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBiodataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBiodataRequest proto.InternalMessageInfo

func (m *DeleteBiodataRequest) GetNik() int32 {
	if m != nil {
		return m.Nik
	}
	return 0
}

type DeleteBiodataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBiodataResponse) Reset()         { *m = DeleteBiodataResponse{} }
func (m *DeleteBiodataResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBiodataResponse) ProtoMessage()    {}
func (*DeleteBiodataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{8}
}

func (m *DeleteBiodataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBiodataResponse.Unmarshal(m, b)
}
func (m *DeleteBiodataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBiodataResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBiodataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBiodataResponse.Merge(m, src)
}
func (m *DeleteBiodataResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBiodataResponse.Size(m)
}
func (m *DeleteBiodataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBiodataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBiodataResponse proto.InternalMessageInfo

type ListBiodataRequest struct {
	Limit                int32    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBiodataRequest) Reset()         { *m = ListBiodataRequest{} }
func (m *ListBiodataRequest) String() string { return proto.CompactTextString(m) }
func (*ListBiodataRequest) ProtoMessage()    {}
func (*ListBiodataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{9}
}

func (m *ListBiodataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBiodataRequest.Unmarshal(m, b)
}
func (m *ListBiodataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBiodataRequest.Marshal(b, m, deterministic)
}
func (m *ListBiodataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBiodataRequest.Merge(m, src)
}
func (m *ListBiodataRequest) XXX_Size() int {
	return xxx_messageInfo_ListBiodataRequest.Size(m)
}
func (m *ListBiodataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBiodataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBiodataRequest proto.InternalMessageInfo

func (m *ListBiodataRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListBiodataResponse struct {
	Biodata              []*Biodata `protobuf:"bytes,1,rep,name=biodata,proto3" json:"biodata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListBiodataResponse) Reset()         { *m = ListBiodataResponse{} }
func (m *ListBiodataResponse) String() string { return proto.CompactTextString(m) }
func (*ListBiodataResponse) ProtoMessage()    {}
func (*ListBiodataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a6ffcb10c2b49dc, []int{10}
}

func (m *ListBiodataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBiodataResponse.Unmarshal(m, b)
}
func (m *ListBiodataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBiodataResponse.Marshal(b, m, deterministic)
}
func (m *ListBiodataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBiodataResponse.Merge(m, src)
}
func (m *ListBiodataResponse) XXX_Size() int {
	return xxx_messageInfo_ListBiodataResponse.Size(m)
}
func (m *ListBiodataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBiodataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBiodataResponse proto.InternalMessageInfo

func (m *ListBiodataResponse) GetBiodata() []*Biodata {
	if m != nil {
		return m.Biodata
	}
	return nil
}

func init() {
	proto.RegisterType((*Biodata)(nil), "proto.Biodata")
	proto.RegisterType((*CreateBiodataRequest)(nil), "proto.CreateBiodataRequest")
	proto.RegisterType((*CreateBiodataResponse)(nil), "proto.CreateBiodataResponse")
	proto.RegisterType((*ReadBiodataRequest)(nil), "proto.ReadBiodataRequest")
	proto.RegisterType((*ReadBiodataResponse)(nil), "proto.ReadBiodataResponse")
	proto.RegisterType((*UpdateBiodataRequest)(nil), "proto.UpdateBiodataRequest")
	proto.RegisterType((*UpdateBiodataResponse)(nil), "proto.UpdateBiodataResponse")
	proto.RegisterType((*DeleteBiodataRequest)(nil), "proto.DeleteBiodataRequest")
	proto.RegisterType((*DeleteBiodataResponse)(nil), "proto.DeleteBiodataResponse")
	proto.RegisterType((*ListBiodataRequest)(nil), "proto.ListBiodataRequest")
	proto.RegisterType((*ListBiodataResponse)(nil), "proto.ListBiodataResponse")
}

func init() {
	proto.RegisterFile("proto/biodata/biodata.proto", fileDescriptor_3a6ffcb10c2b49dc)
}

var fileDescriptor_3a6ffcb10c2b49dc = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcd, 0x6e, 0xb3, 0x30,
	0x10, 0x54, 0x20, 0x3f, 0xfa, 0x36, 0x22, 0xfa, 0xb4, 0x25, 0x2d, 0x25, 0x3d, 0x44, 0x1c, 0x2a,
	0xd4, 0x43, 0x2a, 0xa5, 0x0f, 0xd0, 0x34, 0xcd, 0x09, 0xf5, 0x84, 0x54, 0xf5, 0xec, 0x08, 0x1f,
	0x1c, 0x7e, 0x1b, 0xdc, 0x47, 0xef, 0xbd, 0xc2, 0x18, 0x2b, 0x80, 0x55, 0x09, 0xf5, 0x84, 0xbd,
	0x3b, 0xcc, 0xce, 0xec, 0x18, 0x56, 0xc5, 0x39, 0xe7, 0xf9, 0xe3, 0x91, 0xe5, 0x11, 0xe1, 0xa4,
	0xf9, 0x6e, 0x44, 0x15, 0x27, 0xe2, 0xe3, 0x7d, 0xc0, 0x6c, 0x5f, 0xd7, 0xf1, 0x3f, 0x98, 0x19,
	0x8b, 0x9d, 0xd1, 0x7a, 0xe4, 0x4f, 0xc2, 0xea, 0x88, 0x08, 0xe3, 0x8c, 0xa4, 0xc4, 0x31, 0xd6,
	0x23, 0xff, 0x5f, 0x28, 0xce, 0xb8, 0x00, 0xe3, 0x14, 0x3b, 0xa6, 0xa8, 0x18, 0xa7, 0x18, 0xaf,
	0x61, 0x4a, 0x12, 0x92, 0x12, 0xee, 0x8c, 0x45, 0x4d, 0xde, 0xbc, 0x1d, 0xd8, 0xaf, 0x67, 0x4a,
	0x38, 0x95, 0xf4, 0x21, 0xfd, 0xfc, 0xa2, 0x25, 0x47, 0x1f, 0x66, 0x52, 0x88, 0x98, 0x34, 0xdf,
	0x2e, 0x6a, 0x41, 0x9b, 0x06, 0xd7, 0xb4, 0xbd, 0x17, 0x58, 0x76, 0x18, 0xca, 0x22, 0xcf, 0x4a,
	0x3a, 0x80, 0xe2, 0x1e, 0x30, 0xa4, 0x24, 0xea, 0x48, 0xe8, 0x19, 0xf5, 0x9e, 0xe1, 0xaa, 0x85,
	0x1b, 0x3c, 0x68, 0x07, 0xf6, 0x7b, 0x11, 0xfd, 0xd1, 0x6d, 0x87, 0x61, 0xb0, 0x08, 0x1f, 0xec,
	0x03, 0x4d, 0x68, 0x4f, 0x44, 0xdf, 0xef, 0x0d, 0x2c, 0x3b, 0xc8, 0x7a, 0x98, 0xf7, 0x00, 0xf8,
	0xc6, 0x4a, 0xde, 0x21, 0xb0, 0x61, 0x92, 0xb0, 0x94, 0x71, 0x49, 0x51, 0x5f, 0xaa, 0xa5, 0xb5,
	0xb0, 0x3a, 0xbd, 0xe6, 0x2f, 0x7a, 0xb7, 0xdf, 0x06, 0x98, 0x7b, 0x96, 0x63, 0x00, 0x56, 0x2b,
	0x68, 0x5c, 0xc9, 0x3f, 0x74, 0x0f, 0xc8, 0xbd, 0xd3, 0x37, 0xe5, 0xf4, 0x03, 0xcc, 0x2f, 0x92,
	0xc4, 0x5b, 0x09, 0xee, 0xbf, 0x02, 0xd7, 0xd5, 0xb5, 0x24, 0x4b, 0x00, 0x56, 0x2b, 0x0c, 0xa5,
	0x48, 0x17, 0xb2, 0x52, 0xa4, 0xcf, 0x2f, 0x00, 0xab, 0xb5, 0x6b, 0xc5, 0xa5, 0xcb, 0x4a, 0x71,
	0x69, 0xe3, 0xa9, 0xdc, 0x5d, 0xac, 0x5c, 0xb9, 0xeb, 0x47, 0xa6, 0xdc, 0x69, 0x12, 0x3a, 0x4e,
	0x45, 0xeb, 0xe9, 0x27, 0x00, 0x00, 0xff, 0xff, 0x82, 0x5c, 0x54, 0x75, 0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BioClient is the client API for Bio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BioClient interface {
	CreateBiodata(ctx context.Context, in *CreateBiodataRequest, opts ...grpc.CallOption) (*CreateBiodataResponse, error)
	ReadBiodata(ctx context.Context, in *ReadBiodataRequest, opts ...grpc.CallOption) (*ReadBiodataResponse, error)
	UpdateBiodata(ctx context.Context, in *UpdateBiodataRequest, opts ...grpc.CallOption) (*UpdateBiodataResponse, error)
	DeleteBiodata(ctx context.Context, in *DeleteBiodataRequest, opts ...grpc.CallOption) (*DeleteBiodataResponse, error)
	ListBiodata(ctx context.Context, in *ListBiodataRequest, opts ...grpc.CallOption) (*ListBiodataResponse, error)
}

type bioClient struct {
	cc grpc.ClientConnInterface
}

func NewBioClient(cc grpc.ClientConnInterface) BioClient {
	return &bioClient{cc}
}

func (c *bioClient) CreateBiodata(ctx context.Context, in *CreateBiodataRequest, opts ...grpc.CallOption) (*CreateBiodataResponse, error) {
	out := new(CreateBiodataResponse)
	err := c.cc.Invoke(ctx, "/proto.Bio/CreateBiodata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bioClient) ReadBiodata(ctx context.Context, in *ReadBiodataRequest, opts ...grpc.CallOption) (*ReadBiodataResponse, error) {
	out := new(ReadBiodataResponse)
	err := c.cc.Invoke(ctx, "/proto.Bio/ReadBiodata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bioClient) UpdateBiodata(ctx context.Context, in *UpdateBiodataRequest, opts ...grpc.CallOption) (*UpdateBiodataResponse, error) {
	out := new(UpdateBiodataResponse)
	err := c.cc.Invoke(ctx, "/proto.Bio/UpdateBiodata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bioClient) DeleteBiodata(ctx context.Context, in *DeleteBiodataRequest, opts ...grpc.CallOption) (*DeleteBiodataResponse, error) {
	out := new(DeleteBiodataResponse)
	err := c.cc.Invoke(ctx, "/proto.Bio/DeleteBiodata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bioClient) ListBiodata(ctx context.Context, in *ListBiodataRequest, opts ...grpc.CallOption) (*ListBiodataResponse, error) {
	out := new(ListBiodataResponse)
	err := c.cc.Invoke(ctx, "/proto.Bio/ListBiodata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BioServer is the server API for Bio service.
type BioServer interface {
	CreateBiodata(context.Context, *CreateBiodataRequest) (*CreateBiodataResponse, error)
	ReadBiodata(context.Context, *ReadBiodataRequest) (*ReadBiodataResponse, error)
	UpdateBiodata(context.Context, *UpdateBiodataRequest) (*UpdateBiodataResponse, error)
	DeleteBiodata(context.Context, *DeleteBiodataRequest) (*DeleteBiodataResponse, error)
	ListBiodata(context.Context, *ListBiodataRequest) (*ListBiodataResponse, error)
}

// UnimplementedBioServer can be embedded to have forward compatible implementations.
type UnimplementedBioServer struct {
}

func (*UnimplementedBioServer) CreateBiodata(ctx context.Context, req *CreateBiodataRequest) (*CreateBiodataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBiodata not implemented")
}
func (*UnimplementedBioServer) ReadBiodata(ctx context.Context, req *ReadBiodataRequest) (*ReadBiodataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBiodata not implemented")
}
func (*UnimplementedBioServer) UpdateBiodata(ctx context.Context, req *UpdateBiodataRequest) (*UpdateBiodataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBiodata not implemented")
}
func (*UnimplementedBioServer) DeleteBiodata(ctx context.Context, req *DeleteBiodataRequest) (*DeleteBiodataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBiodata not implemented")
}
func (*UnimplementedBioServer) ListBiodata(ctx context.Context, req *ListBiodataRequest) (*ListBiodataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBiodata not implemented")
}

func RegisterBioServer(s *grpc.Server, srv BioServer) {
	s.RegisterService(&_Bio_serviceDesc, srv)
}

func _Bio_CreateBiodata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBiodataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServer).CreateBiodata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bio/CreateBiodata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServer).CreateBiodata(ctx, req.(*CreateBiodataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bio_ReadBiodata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBiodataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServer).ReadBiodata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bio/ReadBiodata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServer).ReadBiodata(ctx, req.(*ReadBiodataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bio_UpdateBiodata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBiodataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServer).UpdateBiodata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bio/UpdateBiodata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServer).UpdateBiodata(ctx, req.(*UpdateBiodataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bio_DeleteBiodata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBiodataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServer).DeleteBiodata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bio/DeleteBiodata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServer).DeleteBiodata(ctx, req.(*DeleteBiodataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bio_ListBiodata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBiodataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BioServer).ListBiodata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Bio/ListBiodata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BioServer).ListBiodata(ctx, req.(*ListBiodataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Bio_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Bio",
	HandlerType: (*BioServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBiodata",
			Handler:    _Bio_CreateBiodata_Handler,
		},
		{
			MethodName: "ReadBiodata",
			Handler:    _Bio_ReadBiodata_Handler,
		},
		{
			MethodName: "UpdateBiodata",
			Handler:    _Bio_UpdateBiodata_Handler,
		},
		{
			MethodName: "DeleteBiodata",
			Handler:    _Bio_DeleteBiodata_Handler,
		},
		{
			MethodName: "ListBiodata",
			Handler:    _Bio_ListBiodata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/biodata/biodata.proto",
}
